extend darksidewallet locking
zcash/lightwalletd pull request #434
Opened 2023-05-18 16:09 UTC by LarryRuane

Closes #433. This is a test-only change. It single-threads all darksidewalletd requests. Before this PR, it was assumed that the gRPC caller(s) would single-thread "administrative" (test framework) requests such as `Reset()`, other administrative requests (such as `ApplyStaged()`), and production requests such as any that would invoke the `zcashd` stub handler, `darksideRawRequest()`.

There is strong evidence in the #433 crash stack traces that `darksideRawRequest()` (it's not known which specific request) is running at the same time as `Reset()` -- it was assumed that the wallet tests would ensure that this wasn't possible, as it creates a race condition and is non-deterministic. But the darksidewalletd should protect itself even in situations like this, and that's what this PR does. This PR doesn't change any functional behavior.

2023-05-18 23:00 UTC, pacu requested changes
@LarryRuane I'm testing the branch with the darksidewalletd tests from the SDK and they are failing because lightwalletd is not responding the calls and closes the channel. This doesn't occur on `master`. 

Here I'm resetting dlwd, then staging  blocks from that data set and it would close the channel.

If I do step by step debugger I would get one or two commands further but then it would close the channel. 


```
{"app":"lightwalletd","level":"info","msg":"DarksideReset(saplingActivation=663150)","time":"2023-05-18T19:56:12-03:00"}
{"app":"lightwalletd","level":"info","msg":"DarksideStageBlocks(url=https://raw.githubusercontent.com/zcash-hackworks/darksidewalletd-test-data/master/basic-reorg/663150.txt)","time":"2023-05-18T19:58:17-03:00"}
{"app":"lightwalletd","level":"info","msg":"DarksideStageBlocksDarksideStageBlock(height=663150)","time":"2023-05-18T19:58:18-03:00"}
```

2023-05-23 22:06 UTC, LarryRuane commented
I found a bug (in this PR, not in master) that explains what you're seeing, please try the latest, 0a68f1955528403cfa7ff79a24ad8f8bf721e0b2

2023-05-24 12:32 UTC, pacu commented
I see test failures for those involving retrieving submitted transactions. with this RPC `/cash.z.wallet.sdk.rpc.DarksideStreamer/GetIncomingTransactions`. I'll follow up with more details.

2023-05-26 17:27 UTC, LarryRuane commented
Force-push to fix a `GetIncomingTransactions` bug (introduced only in this PR), @pacu, please try again, it should be fixed.

2023-05-27 13:53 UTC, merged